# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI
on:
  push:
    branches: [ feature/** ]

jobs:
  job1:
    name: Git IDs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Git Id and diff files
      run: |
        echo "Current Commit ID: " $GITHUB_SHA
        sha_pre=$(git rev-list -n 1 $(git describe --tags $(git rev-list --tags --max-count=1)))
        echo "Previous Successful merged Commit ID: " $sha_pre
        export sha_diff=$(git diff --pretty=format: --name-only $GITHUB_SHA $sha_pre)
        echo "$sha_diff" > NewDiff.txt
        cat -n NewDiff.txt

    - name: Upload Diff File
      uses: actions/upload-artifact@v1
      with:
        name: DifferenceFile
        path: NewDiff.txt

  job2:
    name: Running ant commands
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download Diff File
      uses: actions/download-artifact@v4.1.7
      with:
        name: DifferenceFile

    - name: Build with Ant
      run: ant -buildfile build.xml diffBuilderWithGitCommit

    - name: Upload Deploy-sf folder
      uses: actions/upload-artifact@v1
      with:
        name: Diff_Folder
        path: deploy-sf

  job3:
    name: Validation
    needs: job2
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0

    steps:
      - uses: actions/checkout@v1
      - name: Download Diff Folder
        uses: actions/download-artifact@v4.1.7
        with:
          name: Diff_Folder

      - name: Populate auth file with SFDX_URL secret
        shell: bash
        run: echo ${{ secrets.SF_ORG__SIT__AUTH_URL}} > ./SFDX_URL_STORE.txt

      - name: Authenticate against dev hub
        run : sfdx force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=DevHub --setdefaultdevhubusername

      - name: Run Validation against SIT
        run: |
          sfdx force:source:deploy --sourcepath Diff_Folder --checkonly --targetusername DevHub --json >  result.json
          cat result.json | grep -e componentType -e fullName
          jq .result.status result.json
