name: SIT Branch Workflow

on:
  push:
    branches: [SIT]

env:
  TOKEN: ${{ secrets.TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  SF_ORG__SIT__AUTH_URL: ${{ secrets.SF_ORG__SIT__AUTH_URL }}

jobs:
  job1:
    name: Git IDs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Git Id and diff files
      run: |
        echo "Current Commit ID: " $GITHUB_SHA
        sha_pre=$(git rev-list -n 1 $(git describe --tags $(git rev-list --tags --max-count=1)))
        echo "Previous Successful merged Commit ID: " $sha_pre
        export sha_diff=$(git diff --pretty=format: --name-only $GITHUB_SHA $sha_pre)
        echo "$sha_diff" > NewDiff.txt
        cat -n NewDiff.txt

    - name: Upload Diff File
      uses: actions/upload-artifact@v1
      with:
        name: DifferenceFile
        path: NewDiff.txt

  job2:
    name: Running ant commands
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download Diff File
      uses: actions/download-artifact@v4.1.7
      with:
        name: DifferenceFile

    - name: Build with Ant
      run: ant -buildfile build.xml diffBuilderWithGitCommit

    - name: Upload Deploy-sf folder
      uses: actions/upload-artifact@v1
      with:
        name: Diff_Folder
        path: deploy-sf

  job3:
    name: Deployment
    needs: job2
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0

    steps:
      - uses: actions/checkout@v1
      - name: Download Diff Folder
        uses: actions/download-artifact@v4.1.7
        with:
          name: Diff_Folder

      - name: Populate auth file with SFDX_URL secret
        shell: bash
        run: echo ${{ secrets.SF_ORG__SIT__AUTH_URL}} > ./SFDX_URL_STORE.txt

      - name: Authenticate against dev hub
        run : sfdx force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=DevHub --setdefaultdevhubusername

      - name: Run deployment to SIT
        run: |
          sfdx force:source:deploy --sourcepath Diff_Folder --testlevel NoTestRun --targetusername DevHub --json > result.json
          cat result.json | grep -e type -e fullName

  job4:
    name: Tag
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: Checkout branch "SIT"
        uses: actions/checkout@v2
        with:
          ref: 'SIT'
      - name: Tag snapshot
        uses: nitssnatha/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.TOKEN }}
          tag: sit-${{ steps.date.outputs.date }}

